# 服务端：监听公网 44101 raw 端口，把还原的 UDP 转发给本机 UDPspeeder 的 44101。
# raw faketcp 与本机 UDP 使用不同协议，数值相同的端口可以配对使用。
OPTS=-s -l0.0.0.0:44101 -r127.0.0.1:44101 -k spdwg_sg2gz_wjg --raw-mode faketcp --cipher-mode aes128cbc -a
